package main

import "core:fmt"
import "vendor:raylib"

Atom :: struct {
	symbol:            cstring,
	name:              cstring,
	atomic_number:     i32,
	atomic_weight:     f32,
	electronegativity: f32,
	period:            i32,
	group:             i32,
	state:             cstring, // solid, liquid, gas
	color:             raylib.Color,
	canLick:           CanLick, // Can I lick it?
}

CanLick :: enum {
	Sure,
	Maybe,
	ShouldNot,
	PleaseDont,
}

Elements: [118]Atom = {
	{
		symbol = "H",
		name = "Hydrogen",
		atomic_number = 1,
		atomic_weight = 1.008,
		electronegativity = 2.20,
		period = 1,
		group = 1,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "He",
		name = "Helium",
		atomic_number = 2,
		atomic_weight = 4.002602,
		electronegativity = 0.0,
		period = 1,
		group = 18,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Li",
		name = "Lithium",
		atomic_number = 3,
		atomic_weight = 6.94,
		electronegativity = 0.98,
		period = 2,
		group = 1,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Maybe,
	},
	{
		symbol = "Be",
		name = "Beryllium",
		atomic_number = 4,
		atomic_weight = 9.0122,
		electronegativity = 1.57,
		period = 2,
		group = 2,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "B",
		name = "Boron",
		atomic_number = 5,
		atomic_weight = 10.81,
		electronegativity = 2.04,
		period = 2,
		group = 13,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "C",
		name = "Carbon",
		atomic_number = 6,
		atomic_weight = 12.011,
		electronegativity = 2.55,
		period = 2,
		group = 14,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "N",
		name = "Nitrogen",
		atomic_number = 7,
		atomic_weight = 14.007,
		electronegativity = 3.04,
		period = 2,
		group = 15,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "O",
		name = "Oxygen",
		atomic_number = 8,
		atomic_weight = 15.999,
		electronegativity = 3.44,
		period = 2,
		group = 16,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "F",
		name = "Fluorine",
		atomic_number = 9,
		atomic_weight = 18.998403163,
		electronegativity = 3.98,
		period = 2,
		group = 17,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Ne",
		name = "Neon",
		atomic_number = 10,
		atomic_weight = 20.1797,
		electronegativity = 0.0,
		period = 2,
		group = 18,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Na",
		name = "Sodium",
		atomic_number = 11,
		atomic_weight = 22.98976928,
		electronegativity = 0.93,
		period = 3,
		group = 1,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Mg",
		name = "Magnesium",
		atomic_number = 12,
		atomic_weight = 24.305,
		electronegativity = 1.31,
		period = 3,
		group = 2,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Al",
		name = "Aluminum",
		atomic_number = 13,
		atomic_weight = 26.9815385,
		electronegativity = 1.61,
		period = 3,
		group = 13,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Si",
		name = "Silicon",
		atomic_number = 14,
		atomic_weight = 28.085,
		electronegativity = 1.90,
		period = 3,
		group = 14,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "P",
		name = "Phosphorus",
		atomic_number = 15,
		atomic_weight = 30.973761998,
		electronegativity = 2.19,
		period = 3,
		group = 15,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Maybe,
	},
	{
		symbol = "S",
		name = "Sulfur",
		atomic_number = 16,
		atomic_weight = 32.06,
		electronegativity = 2.58,
		period = 3,
		group = 16,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Cl",
		name = "Chlorine",
		atomic_number = 17,
		atomic_weight = 35.45,
		electronegativity = 3.16,
		period = 3,
		group = 17,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Ar",
		name = "Argon",
		atomic_number = 18,
		atomic_weight = 39.948,
		electronegativity = 0.0,
		period = 3,
		group = 18,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "K",
		name = "Potassium",
		atomic_number = 19,
		atomic_weight = 39.0983,
		electronegativity = 0.82,
		period = 4,
		group = 1,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Ca",
		name = "Calcium",
		atomic_number = 20,
		atomic_weight = 40.078,
		electronegativity = 1.00,
		period = 4,
		group = 2,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Sc",
		name = "Scandium",
		atomic_number = 21,
		atomic_weight = 44.955908,
		electronegativity = 1.36,
		period = 4,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Ti",
		name = "Titanium",
		atomic_number = 22,
		atomic_weight = 47.867,
		electronegativity = 1.54,
		period = 4,
		group = 4,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "V",
		name = "Vanadium",
		atomic_number = 23,
		atomic_weight = 50.9415,
		electronegativity = 1.63,
		period = 4,
		group = 5,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Cr",
		name = "Chromium",
		atomic_number = 24,
		atomic_weight = 51.9961,
		electronegativity = 1.66,
		period = 4,
		group = 6,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Mn",
		name = "Manganese",
		atomic_number = 25,
		atomic_weight = 54.938044,
		electronegativity = 1.55,
		period = 4,
		group = 7,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Fe",
		name = "Iron",
		atomic_number = 26,
		atomic_weight = 55.845,
		electronegativity = 1.83,
		period = 4,
		group = 8,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Co",
		name = "Cobalt",
		atomic_number = 27,
		atomic_weight = 58.933194,
		electronegativity = 1.88,
		period = 4,
		group = 9,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Ni",
		name = "Nickel",
		atomic_number = 28,
		atomic_weight = 58.6934,
		electronegativity = 1.91,
		period = 4,
		group = 10,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Cu",
		name = "Copper",
		atomic_number = 29,
		atomic_weight = 63.546,
		electronegativity = 1.90,
		period = 4,
		group = 11,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Zn",
		name = "Zinc",
		atomic_number = 30,
		atomic_weight = 65.38,
		electronegativity = 1.65,
		period = 4,
		group = 12,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Ga",
		name = "Gallium",
		atomic_number = 31,
		atomic_weight = 69.723,
		electronegativity = 1.81,
		period = 4,
		group = 13,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Ge",
		name = "Germanium",
		atomic_number = 32,
		atomic_weight = 72.63,
		electronegativity = 2.01,
		period = 4,
		group = 14,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "As",
		name = "Arsenic",
		atomic_number = 33,
		atomic_weight = 74.921595,
		electronegativity = 2.18,
		period = 4,
		group = 15,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Se",
		name = "Selenium",
		atomic_number = 34,
		atomic_weight = 78.971,
		electronegativity = 2.55,
		period = 4,
		group = 16,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Maybe,
	},
	{
		symbol = "Br",
		name = "Bromine",
		atomic_number = 35,
		atomic_weight = 79.904,
		electronegativity = 2.96,
		period = 4,
		group = 17,
		state = "liquid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Kr",
		name = "Krypton",
		atomic_number = 36,
		atomic_weight = 83.798,
		electronegativity = 3.00,
		period = 4,
		group = 18,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Rb",
		name = "Rubidium",
		atomic_number = 37,
		atomic_weight = 85.4678,
		electronegativity = 0.82,
		period = 5,
		group = 1,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Sr",
		name = "Strontium",
		atomic_number = 38,
		atomic_weight = 87.62,
		electronegativity = 0.95,
		period = 5,
		group = 2,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Y",
		name = "Yttrium",
		atomic_number = 39,
		atomic_weight = 88.90584,
		electronegativity = 1.22,
		period = 5,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Zr",
		name = "Zirconium",
		atomic_number = 40,
		atomic_weight = 91.224,
		electronegativity = 1.33,
		period = 5,
		group = 4,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Nb",
		name = "Niobium",
		atomic_number = 41,
		atomic_weight = 92.90637,
		electronegativity = 1.60,
		period = 5,
		group = 5,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Mo",
		name = "Molybdenum",
		atomic_number = 42,
		atomic_weight = 95.95,
		electronegativity = 2.16,
		period = 5,
		group = 6,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Tc",
		name = "Technetium",
		atomic_number = 43,
		atomic_weight = 98,
		electronegativity = 1.9,
		period = 5,
		group = 7,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Ru",
		name = "Ruthenium",
		atomic_number = 44,
		atomic_weight = 101.07,
		electronegativity = 2.2,
		period = 5,
		group = 8,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Rh",
		name = "Rhodium",
		atomic_number = 45,
		atomic_weight = 102.90550,
		electronegativity = 2.28,
		period = 5,
		group = 9,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Pd",
		name = "Palladium",
		atomic_number = 46,
		atomic_weight = 106.42,
		electronegativity = 2.20,
		period = 5,
		group = 10,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Ag",
		name = "Silver",
		atomic_number = 47,
		atomic_weight = 107.8682,
		electronegativity = 1.93,
		period = 5,
		group = 11,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Cd",
		name = "Cadmium",
		atomic_number = 48,
		atomic_weight = 112.414,
		electronegativity = 1.69,
		period = 5,
		group = 12,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "In",
		name = "Indium",
		atomic_number = 49,
		atomic_weight = 114.818,
		electronegativity = 1.78,
		period = 5,
		group = 13,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Sn",
		name = "Tin",
		atomic_number = 50,
		atomic_weight = 118.710,
		electronegativity = 1.96,
		period = 5,
		group = 14,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Sb",
		name = "Antimony",
		atomic_number = 51,
		atomic_weight = 121.760,
		electronegativity = 2.05,
		period = 5,
		group = 15,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Maybe,
	},
	{
		symbol = "Te",
		name = "Tellurium",
		atomic_number = 52,
		atomic_weight = 127.60,
		electronegativity = 2.10,
		period = 5,
		group = 16,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Maybe,
	},
	{
		symbol = "I",
		name = "Iodine",
		atomic_number = 53,
		atomic_weight = 126.90447,
		electronegativity = 2.66,
		period = 5,
		group = 17,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Xe",
		name = "Xenon",
		atomic_number = 54,
		atomic_weight = 131.293,
		electronegativity = 2.60,
		period = 5,
		group = 18,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Cs",
		name = "Cesium",
		atomic_number = 55,
		atomic_weight = 132.90545196,
		electronegativity = 0.79,
		period = 6,
		group = 1,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Ba",
		name = "Barium",
		atomic_number = 56,
		atomic_weight = 137.327,
		electronegativity = 0.89,
		period = 6,
		group = 2,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "La",
		name = "Lanthanum",
		atomic_number = 57,
		atomic_weight = 138.904,
		electronegativity = 1.10,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Ce",
		name = "Cerium",
		atomic_number = 58,
		atomic_weight = 140.116,
		electronegativity = 1.12,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Pr",
		name = "Praseodymium",
		atomic_number = 59,
		atomic_weight = 140.90766,
		electronegativity = 1.13,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Nd",
		name = "Neodymium",
		atomic_number = 60,
		atomic_weight = 144.242,
		electronegativity = 1.14,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Pm",
		name = "Promethium",
		atomic_number = 61,
		atomic_weight = 145,
		electronegativity = 1.13,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Sm",
		name = "Samarium",
		atomic_number = 62,
		atomic_weight = 150.36,
		electronegativity = 1.17,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Eu",
		name = "Europium",
		atomic_number = 63,
		atomic_weight = 151.964,
		electronegativity = 1.20,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Gd",
		name = "Gadolinium",
		atomic_number = 64,
		atomic_weight = 157.25,
		electronegativity = 1.20,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Tb",
		name = "Terbium",
		atomic_number = 65,
		atomic_weight = 158.92535,
		electronegativity = 1.10,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Dy",
		name = "Dysprosium",
		atomic_number = 66,
		atomic_weight = 162.500,
		electronegativity = 1.22,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Ho",
		name = "Holmium",
		atomic_number = 67,
		atomic_weight = 164.93033,
		electronegativity = 1.23,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Er",
		name = "Erbium",
		atomic_number = 68,
		atomic_weight = 167.259,
		electronegativity = 1.24,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Tm",
		name = "Thulium",
		atomic_number = 69,
		atomic_weight = 168.93422,
		electronegativity = 1.25,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Yb",
		name = "Ytterbium",
		atomic_number = 70,
		atomic_weight = 173.04,
		electronegativity = 1.10,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Lu",
		name = "Lutetium",
		atomic_number = 71,
		atomic_weight = 174.9668,
		electronegativity = 1.27,
		period = 6,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Hf",
		name = "Hafnium",
		atomic_number = 72,
		atomic_weight = 178.49,
		electronegativity = 1.30,
		period = 6,
		group = 4,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Ta",
		name = "Tantalum",
		atomic_number = 73,
		atomic_weight = 180.94788,
		electronegativity = 1.50,
		period = 6,
		group = 5,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "W",
		name = "Tungsten",
		atomic_number = 74,
		atomic_weight = 183.84,
		electronegativity = 2.36,
		period = 6,
		group = 6,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Re",
		name = "Rhenium",
		atomic_number = 75,
		atomic_weight = 186.207,
		electronegativity = 1.90,
		period = 6,
		group = 7,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Os",
		name = "Osmium",
		atomic_number = 76,
		atomic_weight = 190.23,
		electronegativity = 2.20,
		period = 6,
		group = 8,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Maybe,
	},
	{
		symbol = "Ir",
		name = "Iridium",
		atomic_number = 77,
		atomic_weight = 192.217,
		electronegativity = 2.20,
		period = 6,
		group = 9,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Pt",
		name = "Platinum",
		atomic_number = 78,
		atomic_weight = 195.084,
		electronegativity = 2.28,
		period = 6,
		group = 10,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Au",
		name = "Gold",
		atomic_number = 79,
		atomic_weight = 196.966569,
		electronegativity = 2.54,
		period = 6,
		group = 11,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Hg",
		name = "Mercury",
		atomic_number = 80,
		atomic_weight = 200.592,
		electronegativity = 2.00,
		period = 6,
		group = 12,
		state = "liquid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Tl",
		name = "Thallium",
		atomic_number = 81,
		atomic_weight = 204.38,
		electronegativity = 1.62,
		period = 6,
		group = 13,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .ShouldNot,
	},
	{
		symbol = "Pb",
		name = "Lead",
		atomic_number = 82,
		atomic_weight = 207.2,
		electronegativity = 1.87,
		period = 6,
		group = 14,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Maybe,
	},
	{
		symbol = "Bi",
		name = "Bismuth",
		atomic_number = 83,
		atomic_weight = 208.98040,
		electronegativity = 2.02,
		period = 6,
		group = 15,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Sure,
	},
	{
		symbol = "Po",
		name = "Polonium",
		atomic_number = 84,
		atomic_weight = 209,
		electronegativity = 2.0,
		period = 6,
		group = 16,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "At",
		name = "Astatine",
		atomic_number = 85,
		atomic_weight = 210,
		electronegativity = 2.2,
		period = 6,
		group = 17,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Rn",
		name = "Radon",
		atomic_number = 86,
		atomic_weight = 222,
		electronegativity = 0.0,
		period = 6,
		group = 18,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Fr",
		name = "Francium",
		atomic_number = 87,
		atomic_weight = 223,
		electronegativity = 0.7,
		period = 7,
		group = 1,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Ra",
		name = "Radium",
		atomic_number = 88,
		atomic_weight = 226,
		electronegativity = 0.9,
		period = 7,
		group = 2,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Ac",
		name = "Actinium",
		atomic_number = 89,
		atomic_weight = 227,
		electronegativity = 1.1,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Th",
		name = "Thorium",
		atomic_number = 90,
		atomic_weight = 232.03806,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Maybe,
	},
	{
		symbol = "Pa",
		name = "Protactinium",
		atomic_number = 91,
		atomic_weight = 231.03588,
		electronegativity = 1.5,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "U",
		name = "Uranium",
		atomic_number = 92,
		atomic_weight = 238.02891,
		electronegativity = 1.38,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .Maybe,
	},
	{
		symbol = "Np",
		name = "Neptunium",
		atomic_number = 93,
		atomic_weight = 237,
		electronegativity = 1.36,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Pu",
		name = "Plutonium",
		atomic_number = 94,
		atomic_weight = 244,
		electronegativity = 1.28,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Am",
		name = "Americium",
		atomic_number = 95,
		atomic_weight = 243,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Cm",
		name = "Curium",
		atomic_number = 96,
		atomic_weight = 247,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Bk",
		name = "Berkelium",
		atomic_number = 97,
		atomic_weight = 247,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Cf",
		name = "Californium",
		atomic_number = 98,
		atomic_weight = 251,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Es",
		name = "Einsteinium",
		atomic_number = 99,
		atomic_weight = 252,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Fm",
		name = "Fermium",
		atomic_number = 100,
		atomic_weight = 257,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Md",
		name = "Mendelevium",
		atomic_number = 101,
		atomic_weight = 258,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "No",
		name = "Nobelium",
		atomic_number = 102,
		atomic_weight = 259,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Lr",
		name = "Lawrencium",
		atomic_number = 103,
		atomic_weight = 262,
		electronegativity = 1.3,
		period = 7,
		group = 3,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Rf",
		name = "Rutherfordium",
		atomic_number = 104,
		atomic_weight = 267,
		electronegativity = 1.3,
		period = 7,
		group = 4,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Db",
		name = "Dubnium",
		atomic_number = 105,
		atomic_weight = 270,
		electronegativity = 1.3,
		period = 7,
		group = 5,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Sg",
		name = "Seaborgium",
		atomic_number = 106,
		atomic_weight = 271,
		electronegativity = 1.3,
		period = 7,
		group = 6,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Bh",
		name = "Bohrium",
		atomic_number = 107,
		atomic_weight = 270,
		electronegativity = 1.3,
		period = 7,
		group = 7,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Hs",
		name = "Hassium",
		atomic_number = 108,
		atomic_weight = 277,
		electronegativity = 1.3,
		period = 7,
		group = 8,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Mt",
		name = "Meitnerium",
		atomic_number = 109,
		atomic_weight = 276,
		electronegativity = 1.3,
		period = 7,
		group = 9,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Ds",
		name = "Darmstadtium",
		atomic_number = 110,
		atomic_weight = 281,
		electronegativity = 1.3,
		period = 7,
		group = 10,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Rg",
		name = "Roentgenium",
		atomic_number = 111,
		atomic_weight = 282,
		electronegativity = 1.3,
		period = 7,
		group = 11,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Cn",
		name = "Copernicium",
		atomic_number = 112,
		atomic_weight = 285,
		electronegativity = 1.3,
		period = 7,
		group = 12,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Nh",
		name = "Nihonium",
		atomic_number = 113,
		atomic_weight = 286,
		electronegativity = 1.3,
		period = 7,
		group = 13,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Fl",
		name = "Flerovium",
		atomic_number = 114,
		atomic_weight = 289,
		electronegativity = 1.3,
		period = 7,
		group = 14,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Mc",
		name = "Moscovium",
		atomic_number = 115,
		atomic_weight = 288,
		electronegativity = 1.3,
		period = 7,
		group = 15,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Lv",
		name = "Livermorium",
		atomic_number = 116,
		atomic_weight = 293,
		electronegativity = 1.3,
		period = 7,
		group = 16,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Ts",
		name = "Tennessine",
		atomic_number = 117,
		atomic_weight = 294,
		electronegativity = 1.3,
		period = 7,
		group = 17,
		state = "solid",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
	{
		symbol = "Og",
		name = "Oganesson",
		atomic_number = 118,
		atomic_weight = 294,
		electronegativity = 1.3,
		period = 7,
		group = 18,
		state = "gas",
		color = raylib.RAYWHITE,
		canLick = .PleaseDont,
	},
}
